platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0.3'
pod 'Pdef', '~> 1.0.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.2'
pod 'FlurrySDK', '~> 4.3.0'
pod 'SDWebImage', '~> 3.5.1'
pod 'HPGrowingTextView', '~> 1.0.1'
